//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Api.DbRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserComment
    {
        public int CommentId { get; set; }
        public int UserID { get; set; }
        public string Description { get; set; }
        public Nullable<int> PostId { get; set; }
        public Nullable<int> TimeStamp { get; set; }
    
        public virtual User User { get; set; }
    }
}
