//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Api.DbRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserBook()
        {
            this.UserBooksStatus = new HashSet<UserBooksStatu>();
            this.UserFavBooks = new HashSet<UserFavBook>();
        }
    
        public int BookId { get; set; }
        public Nullable<int> BookName { get; set; }
        public Nullable<int> BookPrice { get; set; }
        public string BookAuthor { get; set; }
        public Nullable<int> BookReview { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBooksStatu> UserBooksStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFavBook> UserFavBooks { get; set; }
    }
}
